### PR TITLE
Fixes #36

### LINKED ISSUE #36: [Bug]: Add PR Template
### What happened?

Looking to add the new PR Template released by Github into this repo.

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by 01-DC**
Added Pull Request template in .md format

File:   .github/pull_request_template.md

### CODE REVIEW

**Comment by sadn1ck** [comment]
I am pretty sure templates have to be YAML and not markdown, @hrahul2605 confirm?

**Comment by arnabsen1729** [comment]
> I am pretty sure templates have to be YAML and not markdown, @hrahul2605 confirm?

@sadn1ck  No. Even markdown works. Check [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by sadn1ck** [comment]
Ah cool. LGTM then.


What is stakeholder approval though?

**Comment by arnabsen1729** [comment]
Agree with @sadn1ck. Remove the "Stakeholder approval"

**Comment by 01-DC** [comment]
Removed Stakeholder approval from checklist

**Review by arnabsen1729 — APPROVED** [review]
LGTM :100:

**Pull request merged**
